version: '3.7'

services:

  app:
    container_name: app
    build: ./app
    ports:
      - 3000:3000
  
  api:
    container_name: api
    build: ./api
    ports:
      - 3001:3001

  db:
    container_name: db
    image: "postgres"
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  database-data: # named volumes can be managed easier using docker-compose
    